---
title: "Salmon Indicators Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
---

```{r}
# Load required libraries
pacman::p_load(shiny, tidyverse, ggplot2, leaflet,sf,rnaturalearth)

# Load your data (replace this with your actual data loading code)
populations_LUT <- read_csv("results/populations_LUT.csv") %>%
  dplyr::rename(population = esa_pop_name)

indicators <- read_csv("results/indicators_by_NOAA_pop.csv") %>%
  dplyr::rename(population = esa_pop_name) %>%
  left_join(populations_LUT)


state_map <- ne_states (country = 'United States of America', returnclass = 'sf')%>% 
  filter (name %in% c('Washington','Oregon'))

# The input file geodatabase
fgdb <- "spatial_data/WCR_Salmon_Steelhead_gdb_2015.gdb"
if (file.exists(fgdb)) {
    print("Geodatabase already downloaded!")
} else {
  print("Attempting to download Geodatabase...may take a few mins!")
  url<-"https://www.webapps.nwfsc.noaa.gov/portal/sharing/rest/content/items/097239ff29b44a8b87acc048f0363229/data"
  response <- GET(url, timeout(600))
  content <- content(response, as = "raw")
  writeBin(content, "spatial_data/WCR_Salmon_Steelhead_gdb_2015.zip")
  #download.file(, destfile = "data/WCR_Salmon_Steelhead_gdb_2015.zip", mode = "wb",timeout = 300)
  unzip("spatial_data/WCR_Salmon_Steelhead_gdb_2015.zip", exdir = "spatial_data")
}

noaa_polygons<-st_read(fgdb, layer = "fish")%>%
  st_set_crs(st_crs("+proj=longlat +datum=NAD83 +units=m"))

FallCoho <- noaa_polygons%>%
  filter(
    DPS %in% c(
      "Salmon, coho (Lower Columbia River ESU)",
      "Salmon, coho (Lower Columbia River ESU) - Outside legal area"
    ),
    SPECIES == "CO" & !is.na(NWFSC_POP_ID)
  ) %>%
  group_by(NWFSC_POP_ID)%>%
  summarise()
  
WinterSteelhead <- noaa_polygons%>%
  filter(
    DPS %in% c(
      "Steelhead (Lower Columbia River DPS)",
      "Steelhead (Lower Columbia River DPS) - Outside legal area"
      #could add in Steelhead (Middle Columbia River DPS) and su wi for klickitat and white salmon
    )
  ) %>%
  filter(SPECIES == "ST" & RUN_TIMING == "wi") %>%
  group_by(NWFSC_POP_ID)%>%
  summarise()%>%
  bind_rows(noaa_polygons%>%
    filter(
      DPS %in% c(
        "Salmon, coho (Lower Columbia River ESU)",
        "Salmon, coho (Lower Columbia River ESU) - Outside legal area"
      ),
      SPECIES == "CO" & NWFSC_POP_ID%in%c(134,135,140)
    ) %>%
    group_by(NWFSC_POP_ID)%>%
    mutate(NWFSC_POP_ID=ifelse(NWFSC_POP_ID==135,9991,NWFSC_POP_ID),#Grays
           NWFSC_POP_ID=ifelse(NWFSC_POP_ID==134,9992,NWFSC_POP_ID),#elochoman
           NWFSC_POP_ID=ifelse(NWFSC_POP_ID==140,9993,NWFSC_POP_ID),#Mill -abernathy-germany
           )%>%
    summarise()
  )

SummerSteelhead <- noaa_polygons%>%
  filter(
    DPS %in% c(
      "Steelhead (Lower Columbia River DPS)",
      "Steelhead (Lower Columbia River DPS) - Outside legal area"
    )
  ) %>%
  filter(SPECIES == "ST" & RUN_TIMING == "su") %>%
  group_by(NWFSC_POP_ID)%>%
  summarise()

SpringChinook <- noaa_polygons%>%
  filter(
    DPS %in% c(
      "Salmon, Chinook (Lower Columbia River ESU)",
      "Salmon, Chinook (Lower Columbia River ESU) - Outside legal area"
    )
  ) %>%
  filter(SPECIES == "CK" & RUN_TIMING %in% c("sp","ss")) %>%
  group_by(NWFSC_POP_ID)%>%
  summarise()

FallChinook <- noaa_polygons%>%
  filter(
    DPS %in% c(
      "Salmon, Chinook (Lower Columbia River ESU)",
      "Salmon, Chinook (Lower Columbia River ESU) - Outside legal area"
    )
  ) %>%
  filter(SPECIES == "CK" & RUN_TIMING == "fa") %>%
  group_by(NWFSC_POP_ID)%>%
  summarise()

LateFallChinook <- noaa_polygons%>%
  filter(
    DPS %in% c(
      "Salmon, Chinook (Lower Columbia River ESU)",
      "Salmon, Chinook (Lower Columbia River ESU) - Outside legal area"
    )
  ) %>%
  filter(SPECIES == "CK" & RUN_TIMING == "lf") %>%
  group_by(NWFSC_POP_ID)%>%
  summarise()

FallChum <- noaa_polygons%>%
  filter(
    DPS %in% c(
      "Salmon, chum (Columbia River ESU)",
      "Salmon, chum (Columbia River ESU) - Outside legal area"
    )
  ) %>%
  filter(SPECIES == "CM" & RUN_TIMING == "fa") %>%
  group_by(NWFSC_POP_ID)%>%
  summarise()

SummerChum <- noaa_polygons%>%
  filter(
    DPS %in% c(
      "Salmon, chum (Columbia River ESU)",
      "Salmon, chum (Columbia River ESU) - Outside legal area"
    )
  ) %>%
  filter(SPECIES == "CM" & RUN_TIMING == "su") %>%
  group_by(NWFSC_POP_ID)%>%
  summarise()
```


```{r}
# Shiny app
shinyApp(
  ui = fluidPage(
    # Title
    titlePanel("Lower Columbia Salmon Indicator Dashboard"),
    #logo
    fluidRow(
      column(12, align = "left",
             img(src = "https://privatelands.wdfw.wa.gov/wdfwlogo_clrnotxt.png", height = "160px")
      )
    ),
    # Shiny UI components
    selectInput("species", "Select Species", choices = c("None", unique(indicators$species)), multiple = FALSE),
    selectInput("run", "Select Run", choices = c("None", unique(indicators$run)), multiple = FALSE),
    selectInput("population", "Select Population", choices = c("None", unique(indicators$population)), multiple = FALSE),
    downloadButton("downloadData", "Download Data"),
    
    tags$style("
    #downloadButton {
      clear: both:
    }
    #plot {
      float: left;
    }
    #range_map {
      float: right;
    }
  "),
    #placeholder for the plot
    plotOutput("plot",width = "66%", height = "600px"),  
    # This creates a placeholder for the ,map
    plotOutput("range_map",width = "33%", height = "600px")
  ),

  server = function(input, output, session) {
  # Set initial values to NULL
  updateSelectInput(session, "species", selected = "None")
  updateSelectInput(session, "run", selected = "None")
  updateSelectInput(session, "population", selected = "None")

  # Reactive values
  subset_data_reactive <- reactive({
    indicators %>%
      filter(
        if (input$species != "None") species == input$species else TRUE,
        if (input$run != "None") run == input$run else TRUE,
        if (input$population != "None") population == input$population else TRUE
      ) %>%
      dplyr::select(
        Brood_Year, species, run, population, NMFS_POPID, NOSA, TSA,
        pNOB, pHOS, pNI, total_releases = total
      ) %>%
      pivot_longer(
        values_to = "value",
        names_to = "indicator",
        cols = c(NOSA, TSA, pHOS, pNOB, pNI, total_releases)
      ) %>%
      mutate(indicator = factor(indicator, levels = c("NOSA", "TSA", "pHOS", "pNOB", "pNI", "total_releases")))
  })

  observe({
    species_population_filtered <- indicators %>%
      filter(if (input$species != "None") species == input$species else TRUE) %>%
      filter(if (input$population != "None") population == input$population else TRUE)
    updateSelectInput(session, "run", choices = c("None", unique(species_population_filtered$run)), selected = if (input$run != "None") input$run else "None")
  })

  observe({
    run_population_filtered <- indicators %>%
      filter(if (input$run != "None") run == input$run else TRUE) %>%
      filter(if (input$population != "None") population == input$population else TRUE)
    updateSelectInput(session, "species", choices = c("None", unique(run_population_filtered$species)), selected = if (input$species != "None") input$species else "None")
  })

  observe({
    run_species_filtered <- indicators %>%
      filter(if (input$run != "None") run == input$run else TRUE) %>%
      filter(if (input$species != "None") species == input$species else TRUE)
    updateSelectInput(session, "population", choices = c("None", unique(run_species_filtered$population)), selected = if (input$population != "None") input$population else "None")
  })
  
  #map
  # Render Coho Plot
  output$range_map <- renderPlot({
    if (input$population!="None") {
      Run<-tools::toTitleCase(subset_data_reactive()$run[1])
      Species<-tools::toTitleCase(subset_data_reactive()$species[1])
      
      range_dat<-get(paste0(Run,Species))
    
      range_map<-ggplot() +
        geom_sf(data = state_map, color = "black",fill = "lightgrey") + # Washington state map
        geom_sf(data = range_dat, mapping = aes(geometry = SHAPE),fill="lightblue") +
        geom_sf(data = range_dat, mapping = aes(geometry = SHAPE),fill="lightblue") +
        geom_sf(data = range_dat%>%
                filter(NWFSC_POP_ID==subset_data_reactive()$NMFS_POPID[1]),
              mapping = aes(geometry = SHAPE), fill="darkblue") +
        geom_sf(data = state_map, color = "black",fill=NA) + # Washington state map
        #geom_sf(data=release_locs,mapping=aes(geometry=geometry),size=3)+
        labs(title = paste0(Run," ", Species, " Populations"), fill = NA) +
        ylim(44.75,46.8)+
        xlim(-124,-121)+
        theme(
         plot.title = element_text(size = 18),
         text = element_text(size = 12),  # Adjust the main text size
         axis.text = element_text(size = 12)  # Adjust the axis text size
        # You can add more elements like legend.text, title, etc., if needed
        )+
        theme_minimal()
      
      print(range_map)
    }
  })

  # Render plot
  output$plot <- renderPlot({
    cat("Selected species:", input$species, "\n")
    cat("Selected run:", input$run, "\n")
    cat("Selected population:", input$population, "\n")

    # Plotting code
    filtered_data <- subset_data_reactive()
    # Check the number of unique populations in the filtered data
    unique_populations <- unique(filtered_data$population)

    if (length(unique_populations) == 1) {
      facet_limits <- filtered_data %>%
        group_by(indicator, species) %>%
        mutate(
          minBY = min(Brood_Year),
          maxBY = max(Brood_Year),
          min = 0,
          max = max(value, na.rm = TRUE, nan.rm = TRUE)
        ) %>%
        distinct(minBY, maxBY, min, max) %>%
        pivot_longer(cols = c(minBY, maxBY), values_to = "Brood_Year", names_to = "type") %>%
        pivot_longer(cols = c(min, max), values_to = "value", names_to = "type2") %>%
        dplyr::select(-c(type, type2))

      current_plot <- ggplot(filtered_data, aes(x = Brood_Year, y = value, color = species)) +
        geom_line() +
        geom_point() +
        ylim(0, NA) +
        theme_bw() +
        theme() +
        facet_wrap(~indicator, nrow = 6, scales = "free_y") +
        ggtitle(filtered_data$population[1]) +
        geom_blank(data = facet_limits, aes(x = Brood_Year, y = value))+
        theme(
         plot.title = element_text(size = 18),
         text = element_text(size = 16),  # Adjust the main text size
         axis.text = element_text(size = 14)  # Adjust the axis text size
        # You can add more elements like legend.text, title, etc., if needed
        )

      print(current_plot)
    } else {
      print("Please select only one population to generate the plot.")
    }
  })

  # Download handler
    output$downloadData <- downloadHandler(
      filename = function() {
        paste("salmon_indicator_data_", Sys.Date(), ".csv", sep = "")
      },
      content = function(file) {
        req(subset_data_reactive())
        write.csv(subset_data_reactive(), file, row.names = FALSE)
      }
    )
  }

)

```